This is also a notebook covering the fundamentals of PyTorch. I learned all this from Daniel Bourke's Learn PyTorch in a day (literally) video on youtube.
This is chapter 00 from the tutorial.

In [ ]:
!nvidia-smi # Tells us what GPU our machine is using ^_^ 🫡.

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.0+cu113


In [ ]:
print('Hello! I\'m excited to learn PyTorch')

Hello! I'm excited to learn PyTorch


## Introduction to Tensors

A tensor, according to PyTorch is a n-dimensioned matrix that contains data of similar datatype.

### Creating Tensors

PyTorch tensors are created using torch.tensor()
Assignment: Read through torch.Tensor documentation for 10 mins atleast.


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # Gives us the number of dimensions in our tensor.
# A scalar has 0 dimensions.

0

In [ ]:
# Get scalar back as a python int.
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # You can assume that the dimension is the number of indices required to reference value in the tensor.

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0] # Gives us the tensor at 1st dimension.

tensor([7, 8])

In [ ]:
MATRIX[1] # Gives us the tensor at 2nd dimension.

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,7,8],
                        [2,7,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 7, 8],
         [2, 7, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape  # Gives us number of elements in each dimension.

torch.Size([1, 3, 3])

### Notation:
This is how they're written. Not a compulsion though!
Scalars and Vectors are written lower case. a, b, names, etc.

Matrices and Tensors are written in upper case. X, MATRIX etc.

### Random Tensors

Why random tensors?

Random tensors are important because the neural networks start out with a tensor full of random values and then improve those values according to observations and patterns they see. They change those numbers to better represent that data.

In [ ]:
# Creating a random tensor of size (3,4) or shape(3,4).
random_tensor = torch.rand(3,4)
# The above line is the same as
# random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.1584, 0.6358, 0.9124, 0.8084],
        [0.4251, 0.0469, 0.4741, 0.8343],
        [0.8134, 0.6713, 0.2601, 0.5700]])

In [ ]:
# Creating a random tensor with similar shape to an image tensor.
# Let's suppose, the image is rgb and has resolution 224, 224.
random_image_tensor = torch.rand(size=(224,224,3))  # 224 height, 224 width, 3 channels (R, G, B)

In [ ]:
random_image_tensor.ndim

3

In [ ]:
random_image_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [ ]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor # This is element wise multiplication, so elements at corresponding positions are multiplied.

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Creating a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype  # Tells us the datatype of the object or variable.

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

By default, any tensor created by PyTorch will be of the datatype float32 unless specified.

### Creating a range of Tensors and tensors-like

In [ ]:
# Creating a 1D tensor (vector/array) with a specific number range.
# torch.range(0, 10)  # This function will be deprecated. Instead use torch.arange()
oneToTen = torch.arange(0,10)  # first index included, last index excluded. We can also add a step variable like in python.

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=oneToTen)  # This creates a zero tensor with the same shape as input tensor.
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:-** Tensorflow datatypes are one of the big 3 errors that you'll run into in PyTorch and Deep Learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # Specifies the datatype of the tensor.
                               device=None, # We decide where the tensor is calculated. 'cuda' for gpu. 'cpu' for cpu.
                               requires_grad=False) # Whether or not to track gradients with this tensor's operations.
float_32_tensor.dtype

torch.float32

The above code outputs float32 eventhough we specified dtype as none because, in PyTorch, default datatype for any tensor is float32. We can change that though by explicitly specifying another datatype.

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

#We could also do -
# float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [ ]:
ten = float_16_tensor * float_32_tensor # automatically casts float16 tensor to float32 tensor

In [ ]:
ten.dtype

torch.float32

### Getting information from tensors (Tensor Attributes).
1. Tensors not right datatype - to get datatype of tensor, we use `tensor.dtype`
2. Tensors not right shape - to get shape of tensor, we use `tensor.shape`
3. Tensors not on the right device - to get device of tensor, we use `tensor.device`

In [ ]:
# Create a random tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0290, 0.6415, 0.4318, 0.7625],
        [0.2525, 0.0516, 0.5638, 0.7279],
        [0.3049, 0.0347, 0.4200, 0.8585]])

In [ ]:
some_tensor.dtype # Datatype of tensor

torch.float32

In [ ]:
some_tensor.device  # Device of tensor

device(type='cpu')

In [ ]:
some_tensor.shape # Shape of tensor

torch.Size([3, 4])

In [ ]:
some_tensor.size()  # This is the function that returns the shape too.

torch.Size([3, 4])

### Manipulating Tensors (Tensor Operations)

Tensor operations include -
* Addition
* Subtraction
* Multiplication (Element-Wise)
* Division
* Matrix Multiplication

In [ ]:
# Creating a tensor and adding 10 to it.
tensor = torch.tensor([1,2,3])
tensor + 10 # Adds to each element

tensor([11, 12, 13])

In [ ]:
# Multiplay tensor by 10
tensor * 10 # Multiplies each element by scalar

tensor([10, 20, 30])

In [ ]:
# Try out PyTorch in-built functions.
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication
Two main ways of performing multiplication in Neural Networks and Deep Learning.
1. Element-wise Multiplication
2. Matrix Multiplication (Dot Product)

In [ ]:
# Elememt wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication (Dot Product)
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Why did we get 14 - yaha pe we're multiplying 3x1 with 3x1 which isn't possible.
# This is because, matmul returns dot product if both matrices are 1 dimensional.
# So, it automatically takes transpose of one of the matrices and multiplies that with the other matrix.
# So, solving it by hand, 
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 128 µs, sys: 2.19 ms, total: 2.32 ms
Wall time: 1.85 ms


In [ ]:
%%time
torch.matmul(tensor,tensor) # Much faster compared to above loop that does the same thing.

CPU times: user 70 µs, sys: 0 ns, total: 70 µs
Wall time: 88.9 µs


tensor(14)

### Rules for Matrix Multiplication -
1. The **inner dimensions** must match.
* `(3,2) X (3,2)` won't work
* `(3,2) X (2,3)` will work
* `(2,3) X (3,2)` will work

2. The resulting tensor will have the shape of the outer dimensions.
* `(3,2) X (2,2) = (3,2)`
* `(5,8) X (8,4) = (5,4)`

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))  # This won't work, inner dimensions don't match

RuntimeError: ignored

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,2)).shape

torch.Size([3, 2])

In [ ]:
torch.matmul(torch.rand(5,8), torch.rand(8,4)).shape

torch.Size([5, 4])

### One of the most common errors in deep learning is the shape error.

In [ ]:
tensorA = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensorB = torch.tensor([[7 ,8],
                       [9 ,10],
                       [11,12]])

In [ ]:
# Now if we try to multiply them, we get an error because inner dimensions don't match.
torch.mm(tensorA, tensorB)  # this is an alias function for torch.matmul(). Basically same function called using another name.

RuntimeError: ignored

In [ ]:
# To fix this shape error, we take the transpose of the 2nd or the 1st matrix.
tensorB_transpose = tensorB.T
tensorB_transpose # Row became column, column became row. ^_^.

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
torch.matmul(tensorA, tensorB_transpose)  # Shape error fixed!

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, mean, sum etc (Tensor Aggregation)

In [ ]:
# Creata a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Finding the average
torch.mean(x), x.mean() # ahhahahahhaha tensor not right datatype error.

RuntimeError: ignored

In [ ]:
x.dtype # Our tensor is int64 (Long). But we need float or complex tensor in mean function.

torch.int64

In [ ]:
# Finding the average (again)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Position of min, max values in our tensors.
torch.argmin(x), torch.argmax(x)
# Could also do
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Tensor Manipulation Part 2
We perform the following manipulations on tensors -
* reshape - changes the shape of the tensor to whatever we provide.
* view - create another vector with different shape but that vector shares memory with the original vector.
* stack - concatenating tensors along a single dimension.
* squeeze - Removes the dimensions that have only 1 value in it (i.e dimensions of size 1).
* unsqueeze - Adds single dimension at specified index in the tensor.
* permute - Rearranges the dimensions of the tensor in specified way.

In [ ]:
import torch
x = torch.arange(1, 11, 1)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x_reshaped1 = x.reshape(2,5)
x_reshaped1

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [ ]:
x_reshaped2 = x.reshape(5,2)
x_reshaped2

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
# If the number of elements in the original array does not match the dimensions of new array, we get an error.
x_reshape = x.reshape(3,3)
x_reshape

RuntimeError: ignored

In [ ]:
# Changing the view.
z = x.view(2,5)
z # This z variable shares memory with our original tensor x. So, changing any value in z will change x also.

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [ ]:
z[1,0] = 69
z, x
# As you can see, change reflected in x as well.

(tensor([[ 1,  2,  3,  4,  5],
         [69,  7,  8,  9, 10]]),
 tensor([ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10]))

In [ ]:
# Stacking tensors on top of each other.
x_stacked = torch.stack((x, x, x, x), dim=0)
# dim 0 means that the tensors are added horizontally in the same row one by one. Along the x axis.
x_stacked

tensor([[ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10]])

In [ ]:
x_stacked2 = torch.stack((x,x,x,x), dim=1) 
# dim 1 means stacked along the y axis. Basically same index waale elements are stacked together in a single array.
x_stacked2

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [69, 69, 69, 69],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [ ]:
x_vertical = torch.vstack((x,x,x,x))
x_vertical

tensor([[ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10]])

In [ ]:
x_horizontal = torch.hstack((x,x,x,x))
x_horizontal

tensor([ 1,  2,  3,  4,  5, 69,  7,  8,  9, 10,  1,  2,  3,  4,  5, 69,  7,  8,
         9, 10,  1,  2,  3,  4,  5, 69,  7,  8,  9, 10,  1,  2,  3,  4,  5, 69,
         7,  8,  9, 10])

In [ ]:
# Trying to use torch.squeeze()
zeroTensor = torch.zeros(2,1,2,1,2)
zeroTensor

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
torch.squeeze(zeroTensor) # Basically the same as above but removed the dimensions where only 1 value was present.

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
zeroTensor.shape

torch.Size([2, 1, 2, 1, 2])

In [ ]:
squeezedAlongDim = torch.squeeze(zeroTensor, dim=1)  # Squeezes the tensor only along the dimension at index 1 in shape tuple of the tensor.
squeezedAlongDim.shape

torch.Size([2, 2, 1, 2])

In [ ]:
# Trying to use torch.unsqueeze()
# Adds a single dimension to the target tensor at the specified dim index. Basically the opposite of what squeeze does.

print(f'Squeezed Zero Tensor: \n{squeezedAlongDim}')
print(f'Squeezed Zero Tensor\'s Shape: {squeezedAlongDim.shape}')

unsqueezed = torch.unsqueeze(squeezedAlongDim, dim=1)

print()
print(f'Unsqueezed Zero Tensor: \n{unsqueezed}')
print(f'Unsqueezed Zero Tensor\'s Shape: {unsqueezed.shape}')

Squeezed Zero Tensor: 
tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])
Squeezed Zero Tensor's Shape: torch.Size([2, 2, 1, 2])

Unsqueezed Zero Tensor: 
tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
Unsqueezed Zero Tensor's Shape: torch.Size([2, 1, 2, 1, 2])


You can see, single dimension added at index 1 (because dim=1)

### Permutation -

It retuns a view of the original tensor with rearranged dimensions. It shares the memory with the original tensor so any changes to either of the tensors will change the other one too!

In [ ]:
pTest = torch.randn(2, 3, 5)  # This has shape as (2, 3, 5)
permuted_pTest = torch.permute(pTest, (2, 0, 1))  
# What we're doing is arranging dimensions such that dimension at index 2 in pTest ka shape tuple gets placed at index 0 in the new shape tuple.
# Similarly, our 2nd dimension becomes index 0 of shape tuple of original tensor and, 3rd dimension becomes index 1. 
print(f'Original shape: {pTest.shape}')
print(f'Permuted shape: {permuted_pTest.shape}')

Original shape: torch.Size([2, 3, 5])
Permuted shape: torch.Size([5, 2, 3])


### A better example would be rearranging image data

In [ ]:
img_data = torch.rand(28,28,3)  # [height, width, color]

# Permute(rearrange) the original dimensions.
# We want to rearrange such that color becomes 1st dimension, then height and then width.
img_data_permuted = img_data.permute(2,0,1)  # Shifts dimension 2->0, 0->1, 1->2.

print(f'Original shape: {img_data.shape}')
print(f'Permuted shape: {img_data_permuted.shape}')

Original shape: torch.Size([28, 28, 3])
Permuted shape: torch.Size([3, 28, 28])


In [ ]:
img_data[0, 0, 0] = 420 # Permutation is just a view of the tensor. So changing original tensor changes permutation too.
print(img_data_permuted[0, 0, 0])

tensor(420.)


## Indexing
### Indexing with PyTorch is the similar to indexing with NumPy

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
# Let's index the middle bracket containing 4,5,6
x[0,1]

tensor([4, 5, 6])

In [ ]:
# Can also use other notation.
x[0][1]

tensor([4, 5, 6])

## PyTorch Tensors and Numpy

* Data in Numpy  -> Want in tensor --> `torch.from_numpy(ndarray)`
* Data in tensor -> Want in Numpy  --> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Default datatype in pytorch is float32, whereas it's float64 in numpy.
# When converting from numpy array to pytorch tensor, numpy's default datatype float64 is used unless specified
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
# Change the value of array, what will that do to tensor ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy Array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to numpy_tensor ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of the random)

In short, how neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try to make them better representations of data -> repeat this...`

To reduce the randomness in neural networks and PyTorch, we use the concept of random **seed**. To know what random seed is, watch the khan academy video on Cryptography.

In [ ]:
import torch

tensorA = torch.rand(3, 4)
tensorB = torch.rand(3, 4)

print(tensorA)
print(tensorB)
print(tensorA == tensorB) # Prints the condition for each element of the tensor(WOW!)

tensor([[0.3635, 0.8706, 0.0373, 0.4461],
        [0.0153, 0.9549, 0.5460, 0.2967],
        [0.0163, 0.2187, 0.6573, 0.9268]])
tensor([[0.8199, 0.1536, 0.7903, 0.2416],
        [0.7715, 0.1026, 0.7560, 0.1694],
        [0.6269, 0.7932, 0.5385, 0.8348]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make a random number pattern but make it reproducible.
import torch

# Set the random seed.
RANDOM_SEED = 295 # RIP

torch.manual_seed(RANDOM_SEED)
tensorC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
tensorD = torch.rand(3,4)

print(tensorC)
print(tensorD)
print(tensorC == tensorD) # Prints the condition for each element of the tensor(WOW!)

tensor([[0.2713, 0.8702, 0.8820, 0.9400],
        [0.2000, 0.4267, 0.3424, 0.8355],
        [0.2013, 0.0134, 0.9623, 0.5154]])
tensor([[0.2713, 0.8702, 0.8820, 0.9400],
        [0.2000, 0.4267, 0.3424, 0.8355],
        [0.2013, 0.0134, 0.9623, 0.5154]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

### 1. Getting a GPU.
Easiest way to do that is using colab. You can also access your nvidia gpu if you have one. I have a mac m1 so smh.

In [ ]:
!nvidia-smi

Fri Aug 26 04:38:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Running Torch tensors on GPU.


In [ ]:
import torch
torch.cuda.is_available() # Returns if GPU is available to work on.

True

In [ ]:
# We create a device variable to store what kind of device we're working on
device = 'cuda' if torch.cuda.is_available() else 'cpu' # This is good practice to write device agnostic code.
device

'cuda'

In [ ]:
# Counting the number of GPUs available for us.
torch.cuda.device_count()

1

## Putting tensors (and models) on GPU.

To change the device of the tensor you're working with, you can call the `to(device)` function.

Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:
some_tensor = some_tensor.to(device)

In [ ]:
# Creating a Tensor on CPU.
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [ ]:
# tensorGPU = torch.tensor([1,2,3], device='cuda')
tensorGPU = tensor.to(device) # Creates a copy of our tensor in upper code block and puts it on the gpu.
tensorGPU.device

device(type='cuda', index=0)

## Moving tensors back to CPU.

You would do this if you want to interact with numpy arrays because numpy does not utilize GPUs.
So, let's try using the `torch.Tensor.numpy()` method on our tensor.

In [ ]:
torch.Tensor.numpy(tensorGPU) # This throws an error saying that we can't convert a GPU tensor to numpy array.
# We could also call tensorGPU.numpy() and it would be the same as the above line of code.

TypeError: ignored

In [ ]:
# To fix this issue, we use torch.Tensor.cpu()
# This copies the Tensor to CPU memory so we can change it to arrays and shit.
tensorCPU = torch.Tensor.cpu(tensorGPU).numpy()
tensorCPU

array([1, 2, 3])

## END OF THE FIRST UNIT. NOW WE MOVE ON TO CREATE A MODEL! EXCITING STUFF.

## Exercise Solutions

In [ ]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor = torch.rand((7,7))
tensor

tensor([[0.1650, 0.2612, 0.7121, 0.1250, 0.1524, 0.6331, 0.8452],
        [0.7520, 0.4110, 0.8999, 0.5232, 0.0271, 0.7865, 0.8536],
        [0.6304, 0.1664, 0.5116, 0.0346, 0.0616, 0.4411, 0.6109],
        [0.4282, 0.5123, 0.0234, 0.4680, 0.1241, 0.5615, 0.0980],
        [0.8615, 0.7253, 0.6221, 0.4302, 0.4761, 0.9272, 0.0425],
        [0.0430, 0.0393, 0.5586, 0.1858, 0.1772, 0.7231, 0.4892],
        [0.6744, 0.1010, 0.8842, 0.0683, 0.6634, 0.1482, 0.2380]])

In [ ]:
tensor2 = torch.rand(1,7)
multiplied = torch.matmul(tensor, tensor2.T)
multiplied, multiplied.shape

(tensor([[1.2693],
         [1.8060],
         [0.9356],
         [1.0878],
         [1.6600],
         [0.8066],
         [0.9445]]), torch.Size([7, 1]))

In [ ]:
torch.cuda.manual_seed(1234)
t1 = torch.rand((2,3)).to(device)
t2 = torch.rand((2,3)).to(device)
t1, t2

(tensor([[0.4854, 0.0805, 0.0715],
         [0.6668, 0.3048, 0.4776]], device='cuda:0'),
 tensor([[0.3680, 0.0393, 0.0917],
         [0.5991, 0.9947, 0.0974]], device='cuda:0'))

In [ ]:
mul = torch.matmul(t1, t2.T)
mul

tensor([[0.1883, 0.3779],
        [0.3011, 0.7493]], device='cuda:0')

In [ ]:
maxval = mul.max()
minval = mul.min()

maxval, minval

(tensor(0.7493, device='cuda:0'), tensor(0.1883, device='cuda:0'))

In [ ]:
maxIndex = mul.argmax()
minIndex = mul.argmin()

In [ ]:
torch.cuda.manual_seed(7)
TENSOR = torch.rand((1,1,1,10)).to(device)
changedTensor = TENSOR.squeeze()
TENSOR, changedTensor

(tensor([[[[0.1780, 0.2494, 0.3752, 0.4403, 0.6001, 0.6964, 0.6927, 0.0142,
            0.8724, 0.3349]]]], device='cuda:0'),
 tensor([0.1780, 0.2494, 0.3752, 0.4403, 0.6001, 0.6964, 0.6927, 0.0142, 0.8724,
         0.3349], device='cuda:0'))