# Tensor Basics

#### Importing the Dependencies

In [ ]:
import torch
import numpy

#### Tensor Initialization in PyTorch

In [ ]:
x = torch.empty(2)  # Create an empty 1D tensor
print(x)

tensor([7.0221e-34, 0.0000e+00])


In [ ]:
x = torch.empty(2,2) # Creates a 2D empty tenso
print(x)

tensor([[7.0220e-34, 0.0000e+00],
        [1.5975e-43, 1.3873e-43]])


In [ ]:
x = torch.rand(2,2) # Creates a tensor of random values. The random values are taken from a uniform distribution in range [0, 1)
print(x)

tensor([[0.1440, 0.7970],
        [0.5880, 0.4726]])


In [ ]:
x = torch.zeros(2,2)  # Creates a tensor of all zeros
y = torch.ones(2,2) # Creates a tensor of all ones
print(x.dtype, y.dtype) # .dtype attribute tells us about the data type of the tensor.
y = torch.ones(2,2, dtype=torch.float64)  # We can change the dtype while creating the tensor.
print(x.dtype, y.dtype, y.size()) # The size function gives us the dimensions of the tensor.

torch.float32 torch.float32
torch.float32 torch.float64 torch.Size([2, 2])


In [ ]:
x = torch.tensor([2.5, 0.1]) # We can create a tensor from lists itself.
print(x)

tensor([2.5000, 0.1000])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.1738, 0.3626],
        [0.0730, 0.1765]])
tensor([[0.2582, 0.9569],
        [0.1477, 0.9854]])


#### Basic Mathematical Operations 

In [ ]:
z = x + y # One way of adding two tensors is arithmetically.
print(z)
z = torch.add(x, y) # We can also use add function to do the same.
print(z)

tensor([[0.4319, 1.3195],
        [0.2207, 1.1619]])
tensor([[0.4319, 1.3195],
        [0.2207, 1.1619]])


In [ ]:
# Another thing that we can do is inplace operations. Any function ending with _ in PyTorch does an inplace=True. So it basically modifies the original tensor itself.
y.add_(x) # This adds x to y in the y tensor itself.
print(y)

tensor([[0.4319, 1.3195],
        [0.2207, 1.1619]])


In [ ]:
z = y - x
print(z)
z = torch.sub(y, x) # Subtraction
print(z)

tensor([[0.2582, 0.9569],
        [0.1477, 0.9854]])
tensor([[0.2582, 0.9569],
        [0.1477, 0.9854]])


In [ ]:
z = x * y
print(z)
z = torch.mul(x, y) # Multiplication
print(z)

tensor([[0.0751, 0.4784],
        [0.0161, 0.2051]])
tensor([[0.0751, 0.4784],
        [0.0161, 0.2051]])


In [ ]:
z = x / y
print(z)
z = torch.div(x, y) # Division
print(z)

tensor([[0.4023, 0.2748],
        [0.3307, 0.1519]])
tensor([[0.4023, 0.2748],
        [0.3307, 0.1519]])


#### Slicing Operations 

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[4.2208e-01, 7.5104e-01, 6.7450e-02],
        [8.8575e-01, 9.4554e-01, 3.6370e-03],
        [9.8238e-01, 8.7268e-01, 7.5724e-01],
        [5.8174e-04, 8.5105e-01, 4.7066e-01],
        [3.6281e-02, 2.4006e-01, 6.5388e-01]])


In [ ]:
 print(x[:, 0]) # This prints the first column of the tensor.

tensor([4.2208e-01, 8.8575e-01, 9.8238e-01, 5.8174e-04, 3.6281e-02])


In [ ]:
print(x[0, :])  # This prints only the first row.

tensor([0.4221, 0.7510, 0.0674])


In [ ]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)  # This converts the 4, 4 tensor to a single dimension with 16 values.
print(y, y.size())
# Use -1 if you don't know the dimension and pytorch will automatically determine it. 
z = x.view(-1, 8) # For example here, I want 8 columns but idk how many rows I need for 16 elements so I put -1.
print(z, z.size())

tensor([[0.9463, 0.0982, 0.0578, 0.2945],
        [0.2367, 0.8751, 0.0326, 0.7678],
        [0.7922, 0.5821, 0.1056, 0.3343],
        [0.4391, 0.5571, 0.0460, 0.3433]])
tensor([0.9463, 0.0982, 0.0578, 0.2945, 0.2367, 0.8751, 0.0326, 0.7678, 0.7922,
        0.5821, 0.1056, 0.3343, 0.4391, 0.5571, 0.0460, 0.3433]) torch.Size([16])
tensor([[0.9463, 0.0982, 0.0578, 0.2945, 0.2367, 0.8751, 0.0326, 0.7678],
        [0.7922, 0.5821, 0.1056, 0.3343, 0.4391, 0.5571, 0.0460, 0.3433]]) torch.Size([2, 8])


#### PyTorch to NumPy and vice-versa

In [ ]:
a = torch.ones(5)
print(a)  # This is a pytorch tensor.
b = a.numpy() # To convert tensor to numpy array.
print(b, type(b))  # Type function tells us the type of the object. It's a function from python.

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


Since our tensor is on the CPU, it shares the same memory location with the numpy array. So, modifying the value of the tensor will also change the value of the numpy array.

In [ ]:
a.add_(1) # Adding 1 to each element in the tensor a
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
a = numpy.ones(5)
print(a, type(a))
b = torch.from_numpy(a) # This converts the numpy array to tensor. For numpy arrays, the datatype of the tensor is float64 by default.
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


Here also, modifying one or the other affects the other one. This happens only if the tensor exists on the CPU. If our tensor is on the GPU, then the memory location is not shared and so no changes occur.

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)  # We created the tensor straight away on the GPU.
  y = torch.ones(5) # We created the tensor on the CPU.
  y = y.to(device)  # Moving the created tensor to the GPU.
  z = x + y # This is a new tensor created on the GPU.
  # z.numpy() This function now doesn't work because numpy can't work with tensors on the GPU. So, we move it back to the cpu and then convert.
  # To move it to cpu,
  z = z.to("cpu")
  z = z.numpy()

#### Gradient Tracking or Not ?

In [ ]:
x = torch.ones(5, requires_grad = True) # By default this is false.

This tells PyTorch that it will need to calculate the gradients for this tensor later in the optimization stage of the model.